### PR TITLE
Fix runner deregistration with ACCESS_TOKEN

### LINKED ISSUE #139: Deregistration doesn't appear to be working
It would appear that the logic for deregistering isn't detecting the signal docker swarm is sending to the container.
The only thing I'm doing below is scaling the service to 1 replica, and once it's listening for jobs, scaling it down to 0 replicas.
But the Runners in github are not removed and just accumulate.

Here are the logs for the startup as well as shutdown:
```
2021-09-08 19:59:17	Runner reusage is disabled
2021-09-08 19:59:17	Obtaining the token of the runnet
2021-09-08 19:59:17	Configuring
2021-09-08 19:59:18	--------------------------------------------------------------------------------
2021-09-08 19:59:18	|        ____ _ _   _   _       _          _        _   _                      |
2021-09-08 19:59:18	|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
2021-09-08 19:59:18	|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
2021-09-08 19:59:18	|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
2021-09-08 19:59:18	|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
2021-09-08 19:59:18	|                                                                              |
2021-09-08 19:59:18	|                       Self-hosted runner registration                        |
2021-09-08 19:59:18	|                                                                              |
2021-09-08 19:59:18	--------------------------------------------------------------------------------
2021-09-08 19:59:18	# Authentication
2021-09-08 19:59:21	√ Connected to GitHub
2021-09-08 19:59:23	# Runner Registration
2021-09-08 19:59:24	√ Runner successfully added
2021-09-08 19:59:27	√ Runner connection is good
2021-09-08 19:59:27	# Runner settings
2021-09-08 19:59:27	√ Settings Saved.
2021-09-08 19:59:27	.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
2021-09-08 19:59:27	Starting Runner listener with startup type: service
2021-09-08 19:59:27	Started listener process, pid: 98
2021-09-08 19:59:27	Started running service
2021-09-08 19:59:31	√ Connected to GitHub
2021-09-08 19:59:32	Listening for Jobs
2021-09-08 19:59:49	Shutting down runner listener
2021-09-08 19:59:49	Sending SIGINT to runner listener to stop
2021-09-08 19:59:49	Sending SIGKILL to runner listener
2021-09-08 19:59:49	Shutting down runner listener
2021-09-08 19:59:49	Sending SIGINT to runner listener to stop
2021-09-08 19:59:49	Sending SIGKILL to runner listener
2021-09-08 19:59:49	Exiting...
2021-09-08 19:59:49	Exiting...
2021-09-08 19:59:50	Runner listener exited with error code 143
2021-09-08 19:59:50	Runner listener exit with undefined return code, re-launch runner in 5 seconds.
```

It is being run with the following stack:
```yaml
version: '3.4'

services:
  actions_runner:
    image: myoung34/github-runner:ubuntu-bionic
    environment:
      ACCESS_TOKEN: <redacted>
      RUNNER_NAME_PREFIX: actions_runner
      RUNNER_SCOPE: repo
      REPO_URL: <redacted>
      RUNNER_WORKDIR: "/path/to/workdir/"
    volumes:
      - /path/to/workdir:/path/to/workdir
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: stop-first
```

I've also tried manually going into the container and doing kill -9 1 but i'm still not able to trigger the deregistration flow, unfortunately. Any ideas?

### PR DESCRIPTION
**Pull request by joeyparrish**
This fixes runner deregistration, which needs to have ACCESS_TOKEN still
defined to fetch a fresh RUNNER_TOKEN for deregistration.

The original purpose of unsetting the variables would seem to be for
security, to make sure they unavailable to the jobs running in the
container. Unexporting the variables achieves the same goal, but leaves
them available to the entrypoint later when it runs the deregistration
process.

### CODE REVIEW

**Comment by joeyparrish** [comment]
Without this change, I get this on CTRL-C (with set -x in bash, repo values censored):

```
++ deregister_runner
++ echo 'Caught SIGTERM. Deregistering runner'
+++ bash /token.sh
curl: (22) The requested URL returned error: 401 
++ _TOKEN='{"token": "", "full_url": "https://api.github.com/repos/ORG/REPO/actions/runners/registration-token"}'
+++ echo '{"token": "", "full_url": "https://api.github.com/repos/ORG/REPO/actions/runners/registration-token"}'
+++ jq -r .token
++ RUNNER_TOKEN=
++ ./config.sh remove --token ''

# Runner removal

Enter runner remove token: Failed: Removing runner from the server
Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
++ exit
```

With this change, I get (with set -x in bash, repo and token values censored):

```
++ deregister_runner
++ echo 'Caught SIGTERM. Deregistering runner'
Caught SIGTERM. Deregistering runner
++ [[ -n PAT ]]
+++ ACCESS_TOKEN=PAT
+++ bash /token.sh
++ _TOKEN='{"token": "TOKEN", "full_url": "https://api.github.com/repos/ORG/REPO/actions/runners/registration-token"}'
+++ echo '{"token": "TOKEN", "full_url": "https://api.github.com/repos/ORG/REPO/actions/runners/registration-token"}'
+++ jq -r .token
++ RUNNER_TOKEN=TOKEN
++ ./config.sh remove --token TOKEN

# Runner removal


√ Runner removed successfully
√ Removed .credentials
√ Removed .runner

++ exit
```

It is possible that #139 is not solved by this PR, but I still believe this is a meaningful and correct change.  Please take a look!

**Comment by myoung34** [comment]
There were conflicts from other merges but I attempted to resolve them.
I'll test this today

**Comment by myoung34** [comment]
Im not getting docker to do this properly

```
√ Connected to GitHub

2021-09-15 14:33:12Z: Listening for Jobs
Shutting down runner listener
Sending SIGINT to runner listener to stop
Sending SIGKILL to runner listener
Shutting down runner listener
Sending SIGINT to runner listener to stop
Sending SIGKILL to runner listener
Exiting...
Exiting...
Runner listener exited with error code 143
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
```

thats from a `docker stop {containerid}`
It looks like trap isnt taking effect (with and without `exec` in the entrypoint) and the runner is taking it because its dropped when runsvc.sh kicks it off [here](https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Misc/layoutbin/runsvc.sh)

The javascript that handles it is [here](https://github.com/actions/runner/blob/0a6c34669cbd7c5da3cebd437f07bf872adb7559/src/Misc/layoutbin/RunnerService.js#L90) and [here](https://github.com/actions/runner/blob/0a6c34669cbd7c5da3cebd437f07bf872adb7559/src/Misc/layoutbin/RunnerService.js#L94)

**Comment by myoung34** [comment]
I figured this out and will add a subsequent PR

**Pull request merged**
