### PR TITLE
feat: added mikefarah/yq

### PR DESCRIPTION
**Pull request by ponkio-o**
Hi @myoung34

Thank you for developing this project! 
I have added [mikefarah/yq](https://github.com/mikefarah/yq) to the base docker image. This tool is included in the runner image hosted on GitHub.
ref. https://github.com/actions/runner-images/blob/126c302e7ab88c7960230ba8ffc6c0f8722b4320/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L109

```console
$ docker build -f Dockerfile.base -t docker-github-actions-runner:test .
$ docker run --rm -it docker-github-actions-runner:test bash
root@5e23d58159b5:/# yq --version
yq (https://github.com/mikefarah/yq/) version v4.40.5
```

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by myoung34** [comment]
Tested and worked. Thanks!

**Comment by ponkio-o** [comment]
@myoung34 Thank you for your review!
We use ubuntu jammy based image with release tag in Dockerfile, so can you release new version?

**Comment by ponkio-o** [comment]
@myoung34 Thank you for your review. I have a question about release policy.
We use this docker image with release version tag in Dockerfile. 
```dockerfile
FROM myoung34/github-runner:2.311.0-ubuntu-jammy
...
```

How to use new version (included yq command)? It looks like the release version is tied to [actions/runner](https://github.com/actions/runner), do I need to wait until then?

**Pull request merged**
