### PR TITLE
Build Focal (20.04) images

### PR DESCRIPTION
**Pull request by damacus**

### CODE REVIEW

**Comment by myoung34** [comment]
Transparency: I tried really hard to do this a few weeks back and it went terribly

@damacus let me use this PR as a base and get some good testing in place and I'll see if we can get it in

**Comment by damacus** [comment]
Awesome. If you can let me know what testing you would like to see on the image. I'll see if I can put something together!

**Comment by myoung34** [comment]
I just tested this and it seemed to work as-is, i think whatever i ran into got fixed upstream:

```
2d [myoung:~] 1 % docker exec -it 39757b524e6c /bin/bash
root@39757b524e6c:/actions-runner# which docker
/usr/bin/docker
root@39757b524e6c:/actions-runner# docker ps
CONTAINER ID        IMAGE                                             COMMAND             CREATED             STATUS              PORTS               NAMES
39757b524e6c        octokode/github-runner:ubuntu-focal        "/entrypoint.sh"    25 seconds ago      Up 24 seconds                           github-runner
root@39757b524e6c:/actions-runner# git --version
git version 2.26.2
root@39757b524e6c:/actions-runner# docker-compose --version
docker-compose version 1.26.2, build eefe0d31
root@39757b524e6c:/actions-runner# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
```

**Comment by myoung34** [comment]
Thanks! if these don't build cleanly in actions, i'll subsequently fix it

**Comment by myoung34** [comment]
The issue with focal is isolated to arm/v7: https://github.com/myoung34/docker-github-actions-runner/runs/1004106032?check_suite_focus=true

**Pull request merged**
