### PR TITLE
Add clang and libclang1 to base image

### PR DESCRIPTION
**Pull request by klaus993**
This is needed for several language's libraries, I don't think it makes any harm and it's useful to a bunch of people, including me 😛 

I was wondering if you'd include it in your base image, otherwise I'll have to work with a fork 😄 

Thanks in advance.

### CODE REVIEW

**Comment by klaus993** [comment]
cc @myoung34

**Comment by JulianGro** [comment]
I didn't check very deeply, but according to packages.debian.org this would add at least 80 MiB to the image. 
For reference, I don't use clang in this scenario.

**Comment by klaus993** [comment]
Ah okay, if being as lightweight as possible is a concern, then just close my PR 😄

**Comment by myoung34** [comment]
Ill leave this open as I dont have a personal opinion other than 80 is quite a bit

If others seem to agree we can def add it, but it might be worthwhile to add another build on top of each final output for larger images that contain a lot more packages as an optional pull vs mandatory

**Comment by myoung34** [comment]
Closing for more info/context in #259

**Pull request closed without merging**
