### PR TITLE
Multiarch builds fixed for #4

### PR DESCRIPTION
**Pull request by Pentusha**

### CODE REVIEW

**Comment by myoung34** [comment]
Did you test that this fixes your issue in #4? if so ill merge it as-is

**Comment by Pentusha** [comment]
You could check my build here:
https://github.com/Pentusha/docker-github-actions-runner/actions/runs/35152035

`ubuntu_xenial_deploy` job failed with this log:
```
#34 exporting to image
#34 exporting layers
#34 exporting layers 91.2s done
#34 exporting manifest sha256:f52b31a846a51e385c68f0bb9d1a678ea2220c5dd812bd708ea3393b23fa43b1 0.0s done
#34 exporting config sha256:ddad7f319732ad6eab5ea7bf928254b3fcef172707b236ee3a7da16fa30ed99a done
#34 exporting manifest sha256:c97300819f2ea92f5db872494a747d373054a3f3b3e1dce341058b335f9dc309 done
#34 exporting config sha256:2aba39ce9b24a3dac9e40ec297494338b37e2971c13bd7724029ed306c349b47 done
#34 exporting manifest sha256:eac8de649aeffdf57a9f40d2c06712a5376695008c69ee36be160ee7c73dde41 done
#34 exporting config sha256:a543fee5aa8cc8c8b21373844136bab9636ad2b8803b57d12dc633f0124287b5 done
#34 exporting manifest list sha256:dac993e48ff9e867cbc8980b5faeb29e4356c275fdf01452b79147748ce022fe done
#34 pushing layers
#34 pushing layers 311.2s done
#34 ERROR: failed commit on ref "layer-sha256:f4f8e682c719bd7fa1614ec23e19f9f0c1a3838f72ed19e3aaa868f7d4696cb2": no response
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:f4f8e682c719bd7fa1614ec23e19f9f0c1a3838f72ed19e3aaa868f7d4696cb2": no response
##[error]Process completed with exit code 1.
```
Seems like some IO error while build.

Both other jobs succeed and result images works well.
```bash
➜  ~ arch; docker run -it pentusha/github-runner /actions-runner/bin/Runner.Listener
armv7l
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

What is the URL of your repository? Exiting...
An error occurred: Not configured
```

**Comment by myoung34** [comment]
thanks @Pentusha

**Comment by myoung34** [comment]
Re-releasing 2.165.1 here and on dockerhub with the fix from #5 right now

**Pull request merged**
